from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='inicio'),
    path('solicitudes/', views.solicitudes, name='solicitudes'),
    path('agenda/', views.agenda, name='agenda'),
    path('agenda/nueva/', views.compromiso_nuevo, name='compromiso_nuevo'),
    path('agenda/<int:pk>/estado/<str:estado>/', views.compromiso_estado, name='compromiso_estado'),
    path('agenda/<int:pk>/editar/', views.compromiso_editar, name='compromiso_editar'),
    path('agenda/<int:pk>/eliminar/', views.compromiso_eliminar, name='compromiso_eliminar'),
    path('actividades/', views.actividades, name='actividades'),
    path('actividad/nueva/', views.actividad_nueva, name='actividad_nueva'),
    path('actividad/<str:codigo>/', views.actividad_detalle, name='actividad_detalle'),
    # editar/eliminar deben ir antes de <str:decision>, que tambien los capturaria.
    path('actividad/<str:codigo>/editar/', views.actividad_editar, name='actividad_editar'),
    path('actividad/<str:codigo>/eliminar/', views.actividad_eliminar, name='actividad_eliminar'),
    path('actividad/<str:codigo>/<str:decision>/', views.revisar_actividad, name='revisar_actividad'),
    path('administracion/delegaciones/', views.delegaciones_crud, name='delegaciones_crud'),
    path('administracion/perfiles/', views.perfiles_usuario, name='perfiles_usuario'),
    path('administracion/perfiles/nuevo/', views.perfil_usuario_form, name='perfil_usuario_nuevo'),
    path('administracion/perfiles/<int:pk>/editar/', views.perfil_usuario_form, name='perfil_usuario_editar'),
    path('administracion/perfiles/<int:pk>/eliminar/', views.perfil_usuario_eliminar, name='perfil_usuario_eliminar'),
    path('administracion/periodos/', views.periodos_medicion, name='periodos_medicion'),
    path('administracion/periodos/nuevo/', views.periodo_medicion_form, name='periodo_medicion_nuevo'),
    path('administracion/periodos/<int:pk>/editar/', views.periodo_medicion_form, name='periodo_medicion_editar'),
    path('administracion/periodos/<int:pk>/eliminar/', views.periodo_medicion_eliminar, name='periodo_medicion_eliminar'),
    path('administracion/', views.mantenedores, name='mantenedores'),
    path('administracion/delegaciones/nueva/', views.delegacion_form, name='delegacion_nueva'),
    path('administracion/delegaciones/<int:pk>/editar/', views.delegacion_form, name='delegacion_editar'),
    path('administracion/delegaciones/<int:pk>/estado/', views.delegacion_cambiar_estado, name='delegacion_cambiar_estado'),
    path('administracion/catalogo/', views.catalogo_lista, name='catalogo_lista'),
    path('administracion/catalogo/nuevo/', views.catalogo_form, name='catalogo_nuevo'),
    path('administracion/catalogo/<int:pk>/editar/', views.catalogo_form, name='catalogo_editar'),
    path('administracion/catalogo/<int:pk>/eliminar/', views.catalogo_eliminar, name='catalogo_eliminar'),
    path('administracion/evidencias/', views.evidencia_lista, name='evidencia_lista'),
    path('administracion/evidencias/nueva/', views.evidencia_form, name='evidencia_nueva'),
    path('administracion/evidencias/<int:pk>/editar/', views.evidencia_form, name='evidencia_editar'),
    path('administracion/evidencias/<int:pk>/eliminar/', views.evidencia_eliminar, name='evidencia_eliminar'),
    path('administracion/metas/', views.meta_lista, name='metas_lista'),
    path('administracion/metas/nueva/', views.meta_form, name='meta_nueva'),
    path('administracion/metas/<int:pk>/editar/', views.meta_form, name='meta_editar'),
    path('administracion/metas/<int:pk>/eliminar/', views.meta_eliminar, name='meta_eliminar'),
    # Las rutas especificas de cada CRUD deben ir antes de esta ruta generica.
    path('administracion/<slug:slug>/', views.mantenedor_lista, name='mantenedor_lista'),
    path('territorio/', views.institucional, name='institucional'),
    path('delegacion/<str:nombre>/', views.delegacion_detalle, name='delegacion_detalle'),
]
